---
- name: Configuring Ubuntu post deployment
  hosts: Blue-Ubuntu
  gather_facts: no

  tasks:
    - name: create the ssh directory if it is not there 
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0700

    - name: create authorized_keys file
      file:
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        state: touch
        mode: 0644

    - name: add ssh key
      blockinfile: 
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        block: "{{ public_key }}"
      become: yes

    - name: Create a sudoers drop-in file for no password elevation to root by deployer
      file:
        path: /etc/sudoers.d/480
        state: touch
        mode: 0440
      become: yes

    - name: Add line to file
      blockinfile:
          dest: /etc/sudoers.d/480
          block: "{{ ansible_user }}  ALL=(ALL) NOPASSWD: ALL"
      become: yes

    - name: Change the hostname
      hostname:
        name: "{{ hostname }}"
      become: yes

    - name: Add hostname to hosts file
      lineinfile:
        path: /etc/hosts
        line: '127.0.0.1  {{ hostname }}'
      become: yes

    - name: Copy Netplan configuration file
      template:
        src: /home/liam/SYS480/Playbooks/Milestone-7/Ubuntu-Configs/netplan-config.yaml
        dest: /etc/netplan/netplan-config.yaml
        owner: root
        group: root
        mode: 0600
      become: yes

    - name: Restart system to apply changes
      ansible.builtin.reboot:
      become: yes