---
- name: 
  hosts: blue1-dc
  become: yes
  gather_facts: false

  vars_prompt:
    - name: admin_password
      prompt: "Enter the new password for the Administrator account" 
      private: yes
      confirm: yes

    - name: safe_mode_password
      prompt: "Enter the domain's safe mode password"
      private: yes
      confirm: yes

    - name: domain_admin_user
      prompt: "Enter the new domain admin username"
      private: no
      confirm: yes

    - name: domain_admin_password
      prompt: "Enter the new domain admin password"
      private: yes
      confirm: yes

  tasks:
    - name: Setting the local Administrator password
      win_user:
        name: Administrator
        password: "{{ admin_password }}"
        state: present

    - name: Setting the hostname to blue1-dc
      win_hostname:
        name: "{{ hostname }}"
      register: hostname_changed
    
    - name: Reboot since hostname was changed
      win_reboot:
        msg: "Rebooting due to hostname changed"
        pre_reboot_delay: 15
      when: hostname_changed.reboot_required

    - name: Waiting for blue1-dc to come back online
      wait_for_connection:
        delay: 10
        timeout: 300
      when: hostname_changed.reboot_required

    - name: Install AD-Domain-Services to blue1-dc
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        include_dub_features: yes
        state: present
      register: ad_install

    - name: Reboot if AD Feature installation requires it
      win_reboot:
        msg: "Rebooting due to AD feature installation"
        pre_reboot_delay: 15
      when: ad_install.reboot_required

    - name: Create new Forest and Domain (blue.local)
      win_domain:
        dns_domain_name: blue.local
        safe_mode_password: "{{ safe_mode_password }}"
        install_dns: true
      register: domain_creation

    - name: Reboot after domain creation
      win_reboot:
        msg: "Rebooting due to domain creation"
        pre_reboot_delay: 15
        post_reboot_delay: 60
      when: domain_creation.changed

    - name: Adding a DNS Server Forwarder
      win_shell: |
        Add-DnsServerForwarder -IPAddress 10.0.5.2 -PassThru
        
    - name: Creating OU structure in BLUE.local AD
      win_shell: |

        # Creates blue1 OU
        New-ADOrganizationalUnit -Name "blue1" -Path "OU=blue1,DC=blue,DC=local" -ProtectedFromAccidentalDeletion $true
        
        # Creates Accounts OU 
        New-ADOrganizationalUnit -Name "Accounts" -Path "OU=blue1,DC=blue,DC=local" -ProtectedFromAccidentalDeletion $true
        
        # Creates Groups OU 
        New-ADOrganizationalUnit -Name "Groups" -Path "OU=Accounts,OU=blue1,DC=blue,DC=local" -ProtectedFromAccidentalDeletion $true
        
        # Creates Computers OU
        New-ADOrganizationalUnit -Name "Computers" -Path "OU=blue1,DC=blue,DC=local" -ProtectedFromAccidentalDeletion $true
        
        # Creates Servers OU
        New-ADOrganizationalUnit -Name "Servers" -Path "OU=Computers,OU=blue1,DC=blue,DC=local" -ProtectedFromAccidentalDeletion $true

        # Creates Workstations OU
        New-ADOrganizationalUnit -Name "Workstations" -Path "OU=Computers,OU=blue1,DC=blue,DC=local" -ProtectedFromAccidentalDeletion $true
        
        Write-Output "OU Structure created successfully"
      when: domain_creation.changed


    - name: Creating the new Domain Admin
      win_shell: |
      # Create the new domain admin user
      $securePassword = ConvertTo-SecureString "{{ domain_admin_password }}" -AsPlainText -Force
      New-ADUser -Name "{{ domain_admin_username }}" `
                 -SamAccountName "{{ domain_admin_username }}" `
                 -UserPrinicpalName "{{ domain_admin_username }}@blue.local" `
                 -AccountPassword $securePassword `
                 -Enabled $true `
                 -PasswordNeverExpires $true `
                 -Path "OU=Accounts,OU=blue1,DC=blue,DC=local" `
                 -Description "Domain Admin Account"
      
      # Add user to Domain Admin group
      Add-ADGroupMember -Identiy "Domain Admins" -Members "{{ domain_admin_username }}"

    - name: Restarting the machine to ensure changes
      win_reboot: