all:
  children:
    Windows:
      hosts:
        DC1-Liam:
          ansible_host: 10.0.17.4
          ansible_user: deployer
          ansible_connection: ssh
          ansible_shell_type: powershell
    Linux:
      hosts:
        xubuntu-wan: 
          ansible_host: 10.0.17.100
          ansible_user: liam
          
    Vyos:
      hosts:
        480-fw: 
          ansible_host: 10.0.17.2
          ansible_user: vyos
        blue1-fw: 
          ansible_host: 10.0.17.101
          ansible_user: vyos
          ansible_python_interpreter: /usr/bin/python3.11
          wan_ip: 10.0.17.200
          lan_ip: 10.0.5.2
          lan: 10.0.5.0/24
          nameserver: 10.0.17.4
          gateway: 10.0.17.2
          hostname: blue1-fw